# Generated by Django 4.1.2 on 2022-10-27 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('surname', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('DI', 'Директор'), ('ME', 'Менеджер/Инженер'), ('RA', 'Работник'), ('BU', 'Бухгалтер'), ('RN', 'Руководитель направления'), ('KS', 'Кадровый специалист')], default='RA', max_length=3)),
                ('inn', models.CharField(max_length=256)),
                ('snils', models.CharField(max_length=256)),
                ('passport', models.CharField(max_length=256)),
                ('company', models.CharField(choices=[('GP', 'ГАЗСПЕЦПРОЕКТ'), ('NG', 'Не ГАЗСПЕЦПРОЕКТ')], default='GP', max_length=3)),
                ('division', models.CharField(choices=[('GSP', 'ГАЗСПЕЦПРОЕКТ'), ('PTO', 'Производственно-технический отдел (ПТО)'), ('WGP', 'Водгазпроект')], default='GSP', max_length=3)),
                ('post', models.CharField(max_length=255)),
                ('info_about_relocate', models.CharField(max_length=511)),
                ('attestation', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('retraining', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_notification', models.DateTimeField()),
                ('object_type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('IWrk', 'В работе'), ('PNR', 'ПНР'), ('SOff', 'В работе'), ('SMR', 'СМР'), ('AOff', 'Аварийное откл.')], default='IWrk', max_length=4)),
                ('seasoning', models.CharField(choices=[('Seas', 'Сезонная'), ('Fyea', 'Круглогодичная')], default='Seas', max_length=4)),
                ('cost', models.IntegerField()),
                ('calendar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('completion', models.DateTimeField()),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employees')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='core.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_to_task',
            field=models.ManyToManyField(related_name='employees', to='core.projects'),
        ),
        migrations.AddField(
            model_name='employees',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employees'),
        ),
    ]
