# Generated by Django 4.1.2 on 2022-10-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='attestation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='info_about_relocate',
            field=models.CharField(blank=True, max_length=511),
        ),
        migrations.AlterField(
            model_name='employees',
            name='inn',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='employees',
            name='login',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='passport',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='post',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='retraining',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='snils',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
