# Generated by Django 4.1.2 on 2022-10-27 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employees_address_alter_employees_attestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='date_of_start',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='leader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.employees'),
        ),
    ]
