# Generated by Django 4.1.2 on 2022-10-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employees_date_of_birth_employees_date_of_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_to_task',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.projects'),
        ),
    ]
