# Generated by Django 4.1.2 on 2022-10-27 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employees_employee_to_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_to_task',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='core.projects'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employees'),
        ),
    ]
