# Generated by Django 4.1.2 on 2022-10-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_projects_calendar_alter_employees_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_to_task',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.projects', verbose_name='*'),
        ),
    ]
