# Generated by Django 4.1.2 on 2022-10-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employees_employee_to_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Объекты', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задачи', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_to_project',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.projects', verbose_name='Объекты'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_to_task',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.tasks', verbose_name='Задания'),
        ),
    ]
