# Generated by Django 4.1.2 on 2022-10-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employees_options_alter_messages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.CharField(blank=True, max_length=1023, verbose_name='Задание'),
        ),
    ]
