# Generated by Django 4.1.2 on 2022-11-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tasks_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('status', models.CharField(choices=[('WO', 'Без статуса'), ('CH', 'Черновик'), ('NS', 'На согласовании'), ('CU', 'Действующий'), ('CO', 'Завершённый'), ('RA', 'Расторгнутый'), ('AN', 'Аннулированный')], default='CU', max_length=4, verbose_name='Статус')),
                ('duration', models.DateField(verbose_name='Срок действия')),
                ('doc', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
