# Generated by Django 4.1.2 on 2022-11-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Документы', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_to_document',
            field=models.ManyToManyField(blank=True, related_name='employee_to_doc', to='core.documents', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_to_document',
            field=models.ManyToManyField(blank=True, related_name='project_to_doc', to='core.projects', verbose_name='Объекты'),
        ),
    ]
