# Generated by Django 4.1.2 on 2022-11-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_documents_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_to_document',
            field=models.ManyToManyField(blank=True, related_name='project_to_doc', to='core.documents', verbose_name='Документы'),
        ),
    ]
