# Generated by Django 4.1.2 on 2022-11-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_projects_project_to_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='doc',
            field=models.FileField(blank=True, upload_to='uploads_messages/'),
        ),
    ]
