# Generated by Django 4.1.2 on 2022-11-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_messages_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='doc',
            field=models.FileField(upload_to='uploads_messages/'),
        ),
    ]
