# Generated by Django 4.1.2 on 2022-11-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_messages_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc',
            field=models.FileField(upload_to='uploads/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employees', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='doc',
            field=models.FileField(upload_to='uploads_messages/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='core.tasks', verbose_name='Задание'),
        ),
    ]
