# Generated by Django 4.1.2 on 2022-11-01 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_documents_doc_alter_messages_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.projects', verbose_name='Проект'),
        ),
    ]
