# Generated by Django 4.0.6 on 2022-11-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tasks_done_alter_messages_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='uploads_messages/', verbose_name='Документ'),
        ),
    ]
