# Generated by Django 4.0.6 on 2022-11-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_messages_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='done',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
