# Generated by Django 4.1.2 on 2022-11-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_tasks_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('IWrk', 'В работе'), ('PNR', 'ПНР'), ('SOff', 'Сезон откл.'), ('SMR', 'СМР'), ('AOff', 'Аварийное откл.')], default='IWrk', max_length=4, verbose_name='Статус объекта'),
        ),
    ]
