# Generated by Django 4.0.6 on 2023-01-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_projects_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
