# Generated by Django 4.1.2 on 2023-01-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_messages_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="date_creation",
            field=models.DateField(auto_now=True, verbose_name="Дата договора"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="date_notification",
            field=models.DateField(verbose_name="Дата(для оповещения)"),
        ),
    ]
