# Generated by Django 4.0.6 on 2023-01-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_messages_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена обслуживания'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_creation',
            field=models.DateField(verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_notification',
            field=models.DateField(verbose_name='Дата(для оповещения)'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completion',
            field=models.DateField(verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
