# Generated by Django 4.0.6 on 2023-01-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_messages_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='upload_messages', verbose_name='Документ'),
        ),
    ]
