# Generated by Django 4.1.2 on 2023-01-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_projects_date_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="completion",
            field=models.DateField(verbose_name="Срок выполнения"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="created",
            field=models.DateField(verbose_name="Дата создания"),
        ),
    ]
