# Generated by Django 4.1.2 on 2023-01-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_tasks_completion_alter_tasks_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="cost",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Цена обслуживания"
            ),
        ),
    ]
