# Generated by Django 4.0.6 on 2023-01-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_messages_doc'),
        ('core', '0029_alter_projects_cost'),
    ]

    operations = [
    ]
